Ouvidoria/Controllers/FeedbacksController.cs
using Ouvidoria.Filters;
using Ouvidoria.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class FeedbacksController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        public ActionResult Index()
        {
            ViewBag.registros = this.GetFeedbacks();
            return View();
        }

        public List<Feedback> GetFeedbacks()
        {
            return db.Feedback.Include(e => e.Departamento).Include(e => e.Usuario).ToList();
        }
    }
}

Ouvidoria/Controllers/HomeController.cs
using Ouvidoria.Models;
using Ouvidoria.Service;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getDepoimentosRespondidos()
        {
            var respondidos = DepoimentoService.GetDepoimentosRespondidos();
            var naoRespondidos = DepoimentoService.GetDepoimentosNaoRespondidos();

            return Json(new { respondidos, naoRespondidos }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getDepoimentosRegistrados()
        {
            var feedbacks = DepoimentoService.GetDepoimentosRegistrados();
            return Json(new { feedbacks }, JsonRequestBehavior.AllowGet);
        }
    }
}

Ouvidoria/Controllers/OuvidoriaController.cs
using Microsoft.AspNet.Identity;
using Ouvidoria.Filters;
using Ouvidoria.Models;
using Ouvidoria.Service;
using System;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("1")]
    public class OuvidoriaController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Denuncia()
        {
            var denuncias = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 1);
            return View(denuncias);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Denuncia(Depoimento denuncia)
        {
            if (ModelState.IsValid)
            {
                DepoimentoService.CadastraDepoimento(denuncia);
                TempData["Retorno"] = "Denuncia registrada com sucesso!";
            }
            else
                TempData["Retorno"] = "Por favor, verifique todos os campos!";
            var denuncias = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 1);
            return View(denuncias);
        }


        public ActionResult Elogio()
        {
            var elogios = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 2);
            return View(elogios);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Elogio(Depoimento elogio)
        {
            elogio.idTipoDepoimento = 1;
            elogio.idUsuario = Convert.ToInt32(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                DepoimentoService.CadastraDepoimento(elogio);
                TempData["Retorno"] = "Elogio registrado com sucesso!";
            }
            else
                TempData["Retorno"] = "Por favor, verifique todos os campos!";
            var elogios = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 2);
            return View(elogios);
        }

        public ActionResult Reclamacao()
        {
            var reclamacoes = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 3);
            return View(reclamacoes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reclamacao(Depoimento reclamacao)
        {
            reclamacao.idTipoDepoimento = 3;
            reclamacao.idUsuario = Convert.ToInt32(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                DepoimentoService.CadastraDepoimento(reclamacao);
                TempData["Retorno"] = "Reclamacao registrado com sucesso!";
            }
            else
                TempData["Retorno"] = "Por favor, verifique todos os campos!";
            var reclamacoes = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 3);
            return View(reclamacoes);
        }

        public ActionResult Sugestao()
        {
            var sugestoes = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 4);
            return View(sugestoes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sugestao(Depoimento sugestao)
        {
            sugestao.idTipoDepoimento = 4;
            sugestao.idUsuario = Convert.ToInt32(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                DepoimentoService.CadastraDepoimento(sugestao);
                TempData["Retorno"] = "Sugestao registrado com sucesso!";
            }
            else
                TempData["Retorno"] = "Por favor, verifique todos os campos!";
            var sugestoes = DepoimentoService.RetornaDepoimentos(Convert.ToInt32(User.Identity.GetUserId()), 4);
            return View(sugestoes);
        }

        public ActionResult Feedback()
        {
            if (!DepartamentoService.TemDepartamento())
            {
                TempData["Error"] = "Nao ha departamentos cadastrados. Favor entrar em contato com um administrador.";
                return RedirectToAction("Index");
            }

            var feedbacks = FeedbackService.RetornaFeedbacks(Convert.ToInt32(User.Identity.GetUserId()));
            ViewBag.idDepartamento = new SelectList(db.Departamento, "id", "Nome");
            return View(feedbacks);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Feedback([Bind(Include = "id,Avaliacao,Comentario,idDepartamento")] Feedback depoimento)
        {
            if (ModelState.IsValid)
            {
                depoimento.idUsuario = Convert.ToInt32(User.Identity.GetUserId());
                FeedbackService.CadastraDepoimento(depoimento);
                TempData["Retorno"] = "Feedback registrado com sucesso!";
            }
            else
                TempData["Retorno"] = "Por favor, verifique todos os campos!";
            
            var feedbacks = FeedbackService.RetornaFeedbacks(Convert.ToInt32(User.Identity.GetUserId()));
            ViewBag.idDepartamento = new SelectList(db.Departamento, "id", "Nome");
            return View(feedbacks);
        }

        public ActionResult EditarDepoimento(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var retorno = DepoimentoService.ValidaDepoimento(id, Convert.ToInt32(User.Identity.GetUserId()));

            if (retorno != "")
            {
                TempData["Error"] = retorno;
                return RedirectToAction("Index");
            }

            Depoimento depoimento = DepoimentoService.EncontraDepoimento(id);
            ViewBag.idTipoDepoimento = new SelectList(db.TipoDepoimento, "id", "Tipo", id);
            return View(depoimento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarDepoimento([Bind(Include = "id,Titulo,Descricao,idTipoDepoimento")] Depoimento depoimento)
        {
            if (ModelState.IsValid)
            {
                DepoimentoService.EditaDepoimento(depoimento);
                switch (depoimento.idTipoDepoimento)
                {
                    case 1:
                        return RedirectToAction("Denuncia");
                    case 2:
                        return RedirectToAction("Elogio");
                    case 3:
                        return RedirectToAction("Reclamacao");
                    case 4:
                        return RedirectToAction("Sugestao");
                    default:
                        return RedirectToAction("Index", "Home"); 
                }
            }
            ViewBag.idTipoDepoimento = new SelectList(db.TipoDepoimento, "id", "Tipo", depoimento.idTipoDepoimento);
            return View(depoimento);
        }

        public ActionResult ExcluirDepoimento(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var retorno = DepoimentoService.ValidaDepoimento(id, Convert.ToInt32(User.Identity.GetUserId()));

            if (retorno != "")
            {
                TempData["Error"] = retorno;
                return RedirectToAction("Index");
            }
            Depoimento depoimento = DepoimentoService.EncontraDepoimento(id);
            ViewBag.idTipoDepoimento = new SelectList(db.TipoDepoimento, "id", "Tipo", depoimento.idTipoDepoimento);
            return View(depoimento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirDepoimento(int id)
        {
            DepoimentoService.ExcluiDepoimento(id);
            return RedirectToAction("Index");
        }
    }
}

Ouvidoria/Views/Home/Index.cshtml
<div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('../../img/home1.jpg');"></div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('http://www.colatina.es.gov.br/ti/ouvidoria/imagens/ouvidoria.png');"></div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../img/home3.jpg');"></div>
        </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev" style="color: white;"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next" style="color: white;"></span>
    </a>
</div>

@if (!User.IsInRole("2"))
{
    <div class="section">
        <div class="container-fluid" style="background-color: white; padding-bottom: 100px; padding-top: 50px;">
            <div class="row">
                <div class="col-xs-12 text-center welcome">
                    <h1 class="title">Bem-vindo</h1>
                    <h1>
                        Pronto para fazer
                        <span class="txt-rotate"
                              style="font-weight: bold;"
                              data-rotate='[ "seu elogio?", "sua sugestão?", "sua reclamação?", "sua denúncia?" ]'></span>
                    </h1>
                </div>
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="col-xs-6 col-xs-offset-3 incial-actions">
                        <div class="col-xs-6">
                            <a class="btn btn-default form-control" href="@Url.Action("Login", "Autenticacao")">Entrar</a>
                        </div>
                        <div class="col-xs-6">
                            <a class="btn btn-primary form-control" href="@Url.Action("Cadastrar", "Autenticacao")">Registrar-se</a>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="container-fluid" style="background-image: linear-gradient(#04519b, #044687 60%, #033769)">
            <div class="row icons">
                <div class="col-md-2 col-xs-12 col-sm-6 col-xs-offset-0 col-sm-offset-0">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Questionarios")">
                            <h1><i class="glyphicon glyphicon-comment"></i></h1>
                            <h3>Questionários </h3>
                            <p>Responda os questionários disponíveis!</p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="glyphicon glyphicon-comment"></i></h1>
                            <h3>Questionários </h3>
                            <p>Responda os questionários disponíveis!</p>
                        </div>
                    }
                </div>
                <div class="col-md-2 col-xs-12 col-sm-6 col-xs-offset-0 col-sm-offset-0">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Feedback", "Ouvidoria")">
                            <h1><i class="glyphicon glyphicon-star"></i></h1>
                            <h3>Feedback </h3>
                            <p>Faça seu Feedback de algum departamento!</p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="glyphicon glyphicon-star"></i></h1>
                            <h3>Feedback </h3>
                            <p>Faça seu Feedback de algum departamento!</p>
                        </div>
                    }
                </div>
                <div class="col-md-2 col-xs-12 col-sm-6">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Elogio", "Ouvidoria")">
                            <h1><i class="fa fa-thumbs-up"></i></h1>
                            <h3>Elogie </h3>
                            <p>Faça um elogio aos lanches da Iara Café!</p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="fa fa-thumbs-up"></i></h1>
                            <h3>Elogie </h3>
                            <p>Faça um elogio aos lanches da Iara Café!</p>
                        </div>
                    }
                </div>
                <div class="col-md-2 col-xs-12 col-sm-6">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Sugestao", "Ouvidoria")">
                            <h1><i class="fa fa-lightbulb"></i></h1>
                            <h3>Sugestione </h3>
                            <p>Faça uma sugestão para a instituição!</p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="fa fa-lightbulb"></i></h1>
                            <h3>Sugestione </h3>
                            <p>Faça uma sugestão para a instituição!</p>
                        </div>
                    }
                </div>
                <div class="col-md-2 col-xs-12 col-sm-6">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Reclamacao", "Ouvidoria")">
                            <h1><i class="fa fa-frown"></i></h1>
                            <h3>Reclame</h3>
                            <p>Faça aqui uma reclamação daquele professor ou funcionário super legal!</p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="fa fa-frown"></i></h1>
                            <h3>Reclame</h3>
                            <p>Faça aqui uma reclamação daquele professor ou funcionário super legal!</p>
                        </div>
                    }
                </div>
                <div class="col-md-2 col-xs-12 col-sm-6 col-md-offset-0 col-xs-offset-0 col-sm-offset-3">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("1"))
                    {
                        <a class="col-xs-12 item btn-active" href="@Url.Action("Denuncia", "Ouvidoria")">
                            <h1><i class="fa fa-bullhorn"></i></h1>
                            <h3>Denuncie </h3>
                            <p>Faça aqui suas denúncias de abuso feita por aquele professor que tirou sua nota! </p>
                        </a>
                    }
                    else
                    {
                        <div class="col-xs-12 item">
                            <h1><i class="fa fa-bullhorn"></i></h1>
                            <h3>Denuncie </h3>
                            <p>Faça aqui suas denúncias de abuso feita por aquele professor que tirou sua nota! </p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

@if (User.Identity.IsAuthenticated && User.IsInRole("2"))
{
    <div class="section">
        <div class="container-fluid" style="background-color: #f7f7f7">
            <div class="row" style="background-image: linear-gradient(#04519b, #044687 60%, #033769);">
                <h2 style="text-align: center; color: white; margin: 10px 0 10px 0;">Relatórios</h2>
            </div>
            <div class="row relatorios">
                <div class="col-md-5 col-md-offset-1">
                    <div class="col-md-12 relatorio">
                        <div id="respondidos"></div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="col-md-12 relatorio">
                        <div id="total"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid" style="background-image: linear-gradient(#04519b, #044687 60%, #033769)">
            <div class="row icons">
                <div class="col-md-2 col-xs-12 col-sm-6 col-md-offset-2 col-xs-offset-0 col-sm-offset-0">
                    <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Feedbacks")">
                        <h1><i class="glyphicon glyphicon-star"></i></h1>
                        <h3>Feedbacks </h3>
                        <p>Visualize os Feedbacks cadastrados!</p>
                    </a>
                </div>
                <div class="col-md-2 col-md-offset-0 col-xs-12 col-sm-6">
                    <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Depoimentos")">
                        <h1><i class="fa fa-comments"></i></h1>
                        <h3>Depoimentos </h3>
                        <p>Visualize e responda os Depoimentos cadastrados!</p>
                    </a>
                </div>
                <div class="col-md-2 col-md-offset-0 col-xs-12 col-sm-6">
                    <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Questionarios")">
                        <h1><i class="glyphicon glyphicon-comment"></i></h1>
                        <h3>Questionários </h3>
                        <p>Crie novos questionários ou edite já existentes!</p>
                    </a>
                </div>
                <div class="col-md-2 col-md-offset-0 col-xs-12 col-sm-6">
                    <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Administracao")">
                        <h1><i class="fa fa-cogs"></i></h1>
                        <h3>Administração </h3>
                        <p>Ajuste as funções do sistema!</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

<style>
    .section {
        padding: 0;
        min-height: 175px;
    }
</style>

@if (TempData["ErroAutorizacao"] != null)
{
    <script type="text/javascript">
        alert('@TempData["ErroAutorizacao"]');
    </script>
}

@if (TempData["Error"] != null)
{
    <script type="text/javascript">
        alert('@TempData["Error"]');
    </script>
}


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("getDepoimentosRespondidos", "Home")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                GraficoPopulacional(data);
                return false;
            }
        });

        $.ajax({
            url: '@Url.Action("getDepoimentosRegistrados", "Home")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                GraficoTotal(data);
                return false;
            }
        });

        return false;
    }

    function GraficoPopulacional(response) {
        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
            ['Respondidos', response.respondidos],
            ['Não Respondidos', response.naoRespondidos],
        ]);

        var options = {
            'title': 'Gráfico de Depoimentos Respondidos',
            'height': '250',
        };

        var chart = new google.visualization.PieChart(document.getElementById('respondidos'));
        chart.draw(data, options);
    }

    function GraficoTotal(response) {

        console.log(response);
        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
            ['Denúncias', response.feedbacks[0]],
            ['Elogios', response.feedbacks[1]],
            ['Reclamações', response.feedbacks[2]],
            ['Sugestões', response.feedbacks[3]],
        ]);

        var options = {
            'title': 'Gráfico de Depoimentos',
            'height': '250',
        };

        var chart = new google.visualization.PieChart(document.getElementById('total'));
        chart.draw(data, options);
    }
    
</script>

<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">