Ouvidoria/Models/Questionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Ouvidoria.Models
{
    [Table("Questionario")]
    public class Questionario
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Título")]
        public string Titulo { get; set; }

        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        [Required]
        [Display(Name = "Data de Início")]
        public DateTime DataInicio { get; set; }

        [Required]
        [Display(Name = "Data Final")]
        public DateTime DataFim { get; set; }

        public List<Pergunta> Pergunta  { get; set; }
    }
}

Ouvidoria/Models/Resposta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Ouvidoria.Models
{
    [Table("Resposta")]
    public class Resposta
    {
        public int id { get; set; }

        public string Conclusao { get; set; }

        [ForeignKey("Opcao")]
        public int? idOpcao { get; set; }

        [ForeignKey("Pergunta")]
        public int idPergunta { get; set; }

        public virtual Opcao Opcao { get; set; }

        public virtual Pergunta Pergunta { get; set; }
    }
}

Ouvidoria/Controllers/QuestionariosController.cs
using Microsoft.AspNet.Identity;
using Ouvidoria.Filters;
using Ouvidoria.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    public class QuestionariosController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        [Authorize]
        public ActionResult Index()
        {
            var user = db.Usuario.Find(Convert.ToInt32(User.Identity.GetUserId()));
            if (user.idUsuarioPerfil == 1)
            {
                var respondidos = db.Retorno
                                    .Where(x => x.idUsuario == user.id)
                                    .Select(x => x.idQuestionario)
                                    .ToArray();

                return View(db.Questionario
                              .Where(x => !respondidos.Contains(x.id)
                                       && x.DataFim >= DateTime.Now
                                       && x.DataInicio <= DateTime.Now)
                              .ToList());
            }
            return View(db.Questionario.ToList());
        }

        [AutorizacaoFiltro("2")]
        public ActionResult PreVisualizar(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            Questionario questionario = db.Questionario
                                          .Include(x => x.Pergunta.Select(y => y.Opcao))
                                          .FirstOrDefault(x => x.id == id);

            if (questionario == null)
            {
                TempData["Error"] = "Questionario nao encontrado";
                return RedirectToAction("Index");
            }

            return View(questionario);
        }

        [AutorizacaoFiltro("2")]
        public ActionResult Criar()
        {
            return View();
        }

        [AutorizacaoFiltro("2")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar([Bind(Include = "id,Titulo, Descricao, DataInicio, DataFim, Pergunta, Pergunta.Opcao")] Questionario questionario)
        {
            if (questionario.DataInicio >= questionario.DataFim)
            {
                ModelState.AddModelError("DataFim", "A data final deve ser maior que a data inicial");
            }
            else if (ModelState.IsValid)
            {
                db.Questionario.Add(questionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questionario);
        }

        [AutorizacaoFiltro("2")]
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Questionario questionario = db.Questionario
                                          .Include(x => x.Pergunta.Select(y => y.Opcao))
                                          .FirstOrDefault(x => x.id == id);
            if (questionario == null)
            {
                TempData["Error"] = "Questionario nao encontrado";
                return RedirectToAction("Index");
            }

            if (db.Retorno.Any(x => x.idQuestionario == id))
            {
                TempData["Error"] = "Ja existem respostas para o questionario em questao, o que significa que o mesmo nao pode ser editado";
                return RedirectToAction("Index");
            }

            return View(questionario);
        }

        [AutorizacaoFiltro("2")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "id,Titulo, Descricao, DataInicio, DataFim, Pergunta, Pergunta.Opcao")] Questionario questionario)
        {
            if (questionario.DataInicio >= questionario.DataFim)
            {
                ModelState.AddModelError("DataFim", "A data final deve ser maior que a data inicial");
            }
            else if (ModelState.IsValid)
            {
                foreach (var pergunta in questionario.Pergunta)
                {
                    if (pergunta.id > 0)
                    {
                        if (pergunta.Opcao != null)
                        {
                            foreach (var opcao in pergunta.Opcao)
                            {
                                if (opcao.id > 0)
                                    db.Entry(opcao).State = EntityState.Modified;
                                else
                                    db.Entry(opcao).State = EntityState.Added;
                            }
                        }
                        db.Entry(pergunta).State = EntityState.Modified;
                    }
                    else
                        db.Entry(pergunta).State = EntityState.Added;
                }
                db.Entry(questionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            questionario = db.Questionario
                             .Include(x => x.Pergunta.Select(y => y.Opcao))
                             .FirstOrDefault(x => x.id == questionario.id);

            return View(questionario);
        }

        [AutorizacaoFiltro("1")]
        public ActionResult Responder(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            Questionario questionario = db.Questionario
                                          .Include(x => x.Pergunta.Select(y => y.Opcao))
                                          .FirstOrDefault(x => x.id == id);

            if (questionario == null)
            {
                TempData["Error"] = "Questionario nao encontrado";
                return RedirectToAction("Index");
            }

            var idUsuario = Convert.ToInt32(User.Identity.GetUserId());
            var retorno = db.Retorno
                            .FirstOrDefault(x => x.idQuestionario == questionario.id 
                                              && x.idUsuario == idUsuario);
            if (retorno != null)
            {
                TempData["Error"] = "Questionario ja respondido";
                return RedirectToAction("Index");
            }

            if (questionario.DataInicio > DateTime.Now || questionario.DataFim < DateTime.Now)
            {
                TempData["Error"] = "Questionario fora do periodo de resposta";
                return RedirectToAction("Index");
            }

            return View(questionario);
        }

        [AutorizacaoFiltro("1")]
        [HttpPost]
        public ActionResult Responder([Bind(Include = "id, idQuestionario, Resposta")] Retorno retorno)
        {
            retorno.idUsuario = Convert.ToInt32(User.Identity.GetUserId());
            if (ModelState.IsValid)
            {
                db.Retorno.Add(retorno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Questionario questionario = db.Questionario
                                          .Include(x => x.Pergunta.Select(y => y.Opcao))
                                          .FirstOrDefault(x => x.id == retorno.idQuestionario);
            return View(questionario);
        }

        [AutorizacaoFiltro("2")]
        public ActionResult Respostas(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var retorno = db.Retorno
                            .Include(x => x.Questionario)
                            .Include(x => x.Usuario)
                            .Where(x => x.idQuestionario == id)
                            .ToList();

            if (retorno == null)
            {
                TempData["Error"] = "Respostas nao encontradas";
                return RedirectToAction("Index");
            }
            
            return View(retorno);
        }

        [AutorizacaoFiltro("2")]
        public ActionResult Resposta(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var retorno = db.Retorno
                          .Include(x => x.Questionario)
                          .Include(x => x.Usuario)
                          .Include(x => x.Resposta.Select(y => y.Pergunta))
                          .Include(x => x.Resposta.Select(y => y.Opcao))
                          .FirstOrDefault(x => x.id == id);
            if (retorno == null)
            {
                TempData["Error"] = "Respostas nao encontradas";
                return RedirectToAction("Index");
            }

            return View(retorno);
        }

        [AutorizacaoFiltro("2")]
        [HttpPost]
        public void RemoverOpcoes(int[] opcoes)
        {
            if (opcoes != null)
            {
                var options = (from opcao in db.Opcao
                               where opcoes.Contains(opcao.id)
                               select opcao).ToList();
                foreach (var opcao in options)
                    db.Entry(opcao).State = EntityState.Deleted;
                db.SaveChanges();
            }
        }

        [AutorizacaoFiltro("2")]
        [HttpPost]
        public void RemoverPerguntas(int[] perguntas)
        {
            if (perguntas != null)
            {
                var questions = (from pergunta in db.Pergunta
                                 where perguntas.Contains(pergunta.id)
                                 select pergunta).ToList();
                foreach (var pergunta in questions)
                    db.Entry(pergunta).State = EntityState.Deleted;
                db.SaveChanges();
            }
        }

    }
}

Ouvidoria/Views/Questionarios/Criar.cshtml
@model Ouvidoria.Models.Questionario
<div class="container-fluid">
    <div class="content-sides">
        <div class="col-md-12" id="divInicial">
            <h1>
                <i class="glyphicon glyphicon glyphicon-plus type-gyphi" style="padding: 12px; height: 60px; width: 60px; font-size: 35px;  "></i>
                Novo Questonário
            </h1>
            <hr />
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Questionários", "Index", "Questionarios")
                </li>
                <li class="active" id="liPagina">Novo</li>
            </ol>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-12 text-center">
                            <span class="field-validation-valid text-danger" hidden="hidden" id="span-aviso">Por favor, preencha todos os campos.</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 linhas">
                                <div class="col-md-12">
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 linhas">
                                <div class="col-md-12">
                                    <div class="col-md-8">
                                        @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DataInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 linhas">
                                <div class="col-md-12">
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.DataInicio, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                                        @Html.ValidationMessageFor(model => model.DataInicio, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DataFim, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 linhas">
                                <div class="col-md-12">
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.DataFim, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                                        @Html.ValidationMessageFor(model => model.DataFim, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="div-Perguntas">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Pergunta, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10 linhas" id="Pergunta[0]" opcoes="2">
                                <div class="col-md-12 pergunta">
                                    <div class="col-md-8">
                                        <input type="text" name="Pergunta[0].Descricao" placeholder="Descrição da pergunta" class="form-control descricao" id="Perguntas[0].Descricao"
                                               data-val="true" data-val-maxlength="Tamanho maximo de quinhentos caracteres" data-val-maxlength-max="500"
                                               data-val-minlength="Tamanho minimo de cinco caracteres" data-val-minlength-min="5" data-val-required="O campo Descrição é obrigatório." />
                                        <span class="field-validation-valid text-danger" data-valmsg-for="Pergunta[0].Descricao" data-valmsg-replace="true"></span>
                                    </div>
                                    <div class="col-md-2">
                                        <select name="Pergunta[0].tipo" class="form-control col-md-2 ddl-tipos">
                                            <option value="0">Dissertativa</option>
                                            <option value="1">Objetiva</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <button class="btn btn-primary form-control " id="btn-add-pergunta" style="vertical-align: middle;">Nova Pergunta</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                    <button type="submit" class="btn btn-primary pull-right" id="btn-submit">Salvar</button>
            }
            <template id="template-pergunta">
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2 linhas" id="Pergunta[:qtdPerguntas:]" opcoes="2">
                        <div class="col-md-12 pergunta">
                            <div class="col-md-8">
                                <input type="text" name="Pergunta[:qtdPerguntas:].Descricao" placeholder="Descrição da pergunta" class="form-control txt-descricao"
                                       id="Pergunta[:qtdPerguntas:].Descricao" data-val="true" data-val-maxlength="Tamanho maximo de quinhentos caracteres" data-val-maxlength-max="500"
                                       data-val-minlength="Tamanho minimo de cinco caracteres" data-val-minlength-min="5" data-val-required="O campo Descrição é obrigatório." />
                                <span class="field-validation-valid text-danger" data-valmsg-for="Pergunta[:qtdPerguntas:].Descricao" data-valmsg-replace="true"></span>
                            </div>
                            <div class="col-md-2">
                                <select name="Pergunta[:qtdPerguntas:].tipo" class="form-control col-md-2 ddl-tipo">
                                    <option value="0">Dissertativa</option>
                                    <option value="1">Objetiva</option>
                                </select>
                            </div>
                            <div class="col-md-2 text-center">
                                <button class="btn btn-danger btn-remover-pergunta">
                                    <i class="glyphicon glyphicon-trash" style="vertical-align: middle;"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </template>
            <template id="template-opcao">
                <div class="col-md-12 opcoes">
                    <div class="col-md-2">
                        <label class="control-label lbl-opcao">Opção 1</label>
                    </div>
                    <div class="col-md-4">
                        <input type="text" name=":id:.Opcao[0].Descricao" placeholder="Opção" class="form-control opcao" />
                    </div>
                </div>
                <div class="col-md-12 opcoes">
                    <div class="col-md-2">
                        <label class="control-label lbl-opcao">Opção 2</label>
                    </div>
                    <div class="col-md-4">
                        <input type="text" name=":id:.Opcao[1].Descricao" placeholder="Opção" class="form-control opcao" />
                    </div>
                    <div class="col-md-2 text-center">
                        <button class="btn btn-primary btn-add-opcao">
                            <i class="glyphicon glyphicon-plus-sign" style="vertical-align: middle;"></i>
                        </button>
                    </div>
                </div>
            </template>
            <template id="template-nova-opcao">
                <div class="col-md-12 opcoes">
                    <div class="col-md-2">
                        <label class="control-label lbl-opcao">Opção :indices:</label>
                    </div>
                    <div class="col-md-4">
                        <input type="text" name=":id:.Opcao[:indice:].Descricao" placeholder="Opção" class="form-control opcao" />
                    </div>
                    <div class="col-md-2 text-center">
                        <button class="btn btn-danger btn-remover-opcao">
                            <i class="glyphicon glyphicon-trash" style="vertical-align: middle;"></i>
                        </button>
                    </div>
                </div>
            </template>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/CriarQuestionario.js"></script>
}

Ouvidoria/Views/Questionarios/Index.cshtml
@model IEnumerable<Ouvidoria.Models.Questionario>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h1>
                <i class="glyphicon glyphicon-comment type-gyphi"></i>
            </h1>
        </div>
        <div class="col-xs-12 text-center">
            <h1 class="name-giphy">Questionários</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="list-group">
                @{ int index = 0; }

                @foreach (var item in Model)
                {
                    string estilo = "white";
                    if (index % 2 == 0)
                    {
                        estilo = "#eaeaea";
                    }

                    <li class="list-group-item" style="background: @estilo">
                        <h4 class="list-group-item-heading">
                            <b>Título: </b>@item.Titulo
                            @if (User.IsInRole("2"))
                            {
                                @Html.ActionLink("Editar", "Editar", new { id = item.id }, new { @class = "btn btn-primary btn-sm pull-right" })
                                @Html.ActionLink("Pré Visualizar", "PreVisualizar", new { id = item.id }, new { @class = "btn btn-default btn-sm pull-right" })
                                @Html.ActionLink("Respostas", "Respostas", new { id = item.id }, new { @class = "btn btn-success btn-sm pull-right" })
                            }
                            else
                            {
                                @Html.ActionLink("Responder", "Responder", new { id = item.id }, new { @class = "btn btn-primary btn-sm pull-right" })
                            }
                        </h4>
                        <p>@item.Descricao</p>
                        <small>De <b>@item.DataInicio.ToShortDateString()</b> até <b>@item.DataFim.ToShortDateString()</b></small>
                    </li>
                    index++;
                }
            </ul>
        </div>
        @if (User.IsInRole("2"))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="text-align: right">
                    @Html.ActionLink("Novo Questionário", "Criar", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        }

    </div>
</div>

@if (TempData["Error"] != null)
{
    <script>alert("@TempData["Error"]")</script>
}

Ouvidoria/Views/Questionarios/PreVisualizar.cshtml
@model Ouvidoria.Models.Questionario

<div class="container-fluid">
    <div class="content-sides">
        <div class="col-md-12" id="divInicial">
            <h1>
                <i class="glyphicon glyphicon-list type-gyphi" style="padding: 12px; height: 60px; width: 60px; font-size: 35px;  "></i>
                Questionário - @Html.Label(Model.Titulo)
            </h1>
            <hr />
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Questionários", "Index", "Questionarios")
                </li>
                <li class="active" id="liPagina">Pré Visualizar</li>
            </ol>

            <div class="jumbotron" style="font-size: 16px !important;">
                <h2 class="text-center">@Html.DisplayFor(model => model.Titulo)</h2>
                <br />
                <small>@Html.DisplayFor(model => model.Descricao)</small>
                <br />
                <br />

                @{int i = 0, j = 1; }
                @foreach (var pergunta in Model.Pergunta)
                {
                    <div class="row">
                        <div class="panel panel-default well-lg">
                            @if (pergunta.tipo == Ouvidoria.Models.Pergunta.Tipo.Objetiva)
                            {
                                <label class="form-control-static">@j  - @pergunta.Descricao</label>
                                <hr />
                                if (pergunta.Opcao != null)
                                {
                                    foreach (var opcao in pergunta.Opcao)
                                    {
                                        <p class="radio"><input type="radio" disabled value="@opcao.id" /> @opcao.Descricao</p>
                                    }
                                }
                            }
                            else
                            {
                                <label class="form-control-static">@j  -  @pergunta.Descricao</label>
                                <hr />
                                <textarea class="form-control" rows="3" disabled></textarea>
                            }
                        </div>
                    </div>
                    i++;
                    j++;
                }
            </div>
            <p>
                @Html.ActionLink("Editar", "Editar", new { id = Model.id }) |
                @Html.ActionLink("Voltar para a lista", "Index")
            </p>
        </div>
    </div>
</div>

Ouvidoria/Views/Questionarios/Responder.cshtml
@model Ouvidoria.Models.Questionario

<div class="container-fluid">
    <div class="content-sides">
        <div class="col-md-8 col-md-offset-2">
            <h1>
                <i class="glyphicon glyphicon-comment type-gyphi" style="padding: 12px; height: 60px; width: 60px; font-size: 35px;  "></i>
                Questionários
            </h1>
            <hr />

            <div class="jumbotron" style="font-size: 16px !important;">
                <h2 class="text-center">@Html.DisplayFor(model => model.Titulo)</h2>
                <br />
                <small>@Html.DisplayFor(model => model.Descricao)</small>
                <br />
                <br />
                @using (Html.BeginForm())
                {
                    <input type="number" name="idQuestionario" value="@Model.id" hidden="hidden" />
                    int i = 0, j = 1, k = 0;
                    foreach (var pergunta in Model.Pergunta)
                    {
                        <div class="row">
                            <div class="panel panel-default well-lg">
                                <input type="number" name="Resposta[@i].idPergunta" value="@pergunta.id" hidden="hidden" />
                                @if (pergunta.tipo == Ouvidoria.Models.Pergunta.Tipo.Objetiva)
                                {
                                    <label class="form-control-static">@j  - @pergunta.Descricao</label>
                                    <hr />
                                    if (pergunta.Opcao != null)
                                    {
                                        k = 0;
                                        foreach (var opcao in pergunta.Opcao)
                                        {
                                            if (k == 0)
                                            {
                                                <p class="radio"><input type="radio" name="Resposta[@i].idOpcao" value="@opcao.id" checked /> @opcao.Descricao</p>
                                            }
                                            else
                                            {
                                                <p class="radio"><input type="radio" name="Resposta[@i].idOpcao" value="@opcao.id" /> @opcao.Descricao</p>
                                            }
                                            k++;
                                        }
                                    }
                                }
                                else
                                {
                                    <label class="form-control-static">@j  -  @pergunta.Descricao</label>
                                    <hr />
                                    <textarea class="form-control resposta" name="Resposta[@i].Conclusao" rows="3"></textarea>
                                }
                            </div>
                        </div>
                        i++;
                        j++;
                    }
                    <input class="btn btn-primary pull-right" type="submit" id="btn-submit" value="Responder" />
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript" src="~/Scripts/ResponderQuestionario.js"></script>
}

Ouvidoria/Views/Questionarios/Respostas.cshtml
@model IEnumerable<Ouvidoria.Models.Retorno>

@{
    ViewBag.Title = "Respostas";
}


<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h1>
                <i class="glyphicon glyphicon-comment type-gyphi"></i>
            </h1>
        </div>
        <div class="col-xs-12 text-center">
            <h1 class="name-giphy">Respostas Questionário</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="list-group">
                @foreach (var item in Model)
                {
                    <li class="list-group-item" style="background: #eaeaea">
                        <h4 class="list-group-item-heading">
                            <b>Usuário: </b>@Html.DisplayFor(modelItem => item.Usuario.Nome)
                            @Html.ActionLink("Ver respostas", "Resposta", new { id = item.id }, new { @class = "btn btn-primary btn-sm pull-right" })
                        </h4>
                        <p>@Html.DisplayFor(modelItem => item.Questionario.Titulo)</p>
                        <small>@Html.DisplayFor(modelItem => item.DataRetorno)</small>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>