Ouvidoria/Controllers/AdministracaoController.cs
using Ouvidoria.Filters;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class AdministracaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Ouvidoria/Controllers/CursosController.cs
using Ouvidoria.Filters;
using Ouvidoria.Models;
using Ouvidoria.Service;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class CursosController : Controller
    {
        public ActionResult Index()
        {
            return View(CursoService.RetornaCursos());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var retorno = CursoService.ValidaCurso(id);
            if (retorno != "")
            {
                TempData["Error"] = retorno;
                return RedirectToAction("Index");
            }
            return View(CursoService.RetornaCurso(id));
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Nome")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                CursoService.CadastrarCurso(curso);
                return RedirectToAction("Index");
            }

            return View(curso);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var retorno = CursoService.ValidaCurso(id);
            if (retorno != "")
            {
                TempData["Error"] = retorno;
                return RedirectToAction("Index");
            }
            return View(CursoService.RetornaCurso(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Nome")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                CursoService.EditarCurso(curso);
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var retorno = CursoService.ValidaCurso(id);
            if (retorno != "")
            {
                TempData["Error"] = retorno;
                return RedirectToAction("Index");
            }
            return View(CursoService.RetornaCurso(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CursoService.DeletarCurso(id);
            return RedirectToAction("Index");
        }

    }
}

Ouvidoria/Controllers/UsuariosController.cs
using Ouvidoria.Filters;
using Ouvidoria.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class UsuariosController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();
        
        public ActionResult Index()
        {
            var usuario = db.Usuario.Include(u => u.Curso).Include(u => u.UsuarioPerfil);
            return View(usuario.ToList());
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario
                              .Include(u => u.Curso)
                              .Include(u => u.UsuarioPerfil)
                              .SingleOrDefault(x => x.id == id);
                              //.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        public ActionResult Create()
        {
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome");
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Nome,Email,Telefone,idCurso,idUsuarioPerfil")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Nome,Email,Telefone,Senha, Ativo, idCurso,idUsuarioPerfil")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ouvidoria/Views/Administracao/Index.cshtml
<section>
    <div class="container-fluid" style="background-color: white; padding-bottom: 100px; padding-top: 50px;">
        <div class="row">
            <div class="col-xs-12 text-center welcome">
                <h1 class="title">
                    <i class="fa fa-cogs"></i>
                    Administração
                </h1>
                <h3>Gerencie seu sistema</h3>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid" style="background-image: linear-gradient(#04519b, #044687 60%, #033769)">
        <div class="row icons">
            <div class="col-md-2 col-xs-12 col-sm-6 col-md-offset-1 col-xs-offset-0 col-sm-offset-3">
                <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Cursos")">
                    <h1><i class="glyphicon glyphicon-asterisk"></i></h1>
                    <h3>Cursos </h3>
                    <p>Cadastre, edite ou visualize todos os cursos da Faculdade. </p>
                </a>
            </div>
            <div class="col-md-2 col-xs-12 col-sm-6 col-md-offset-2 col-xs-offset-0 col-sm-offset-3">
                <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Departamentos")">
                    <h1><i class="glyphicon glyphicon-briefcase"></i></h1>
                    <h3>Departamentos </h3>
                    <p>Cadastre, edite e visualize os departamentos para que os usuários possam deixar o seu Feedback. </p>
                </a>
            </div>
            <div class="col-md-2 col-xs-12 col-sm-6 col-md-offset-2 col-xs-offset-0 col-sm-offset-3">
                <a class="col-xs-12 item btn-active" href="@Url.Action("Index", "Usuarios")">
                    <h1><i class="glyphicon glyphicon-user"></i></h1>
                    <h3>Usuários </h3>
                    <p>Altere ou visualize os dados de um usuário cadastrado no sistema. </p>
                </a>
            </div>
        </div>
    </div>
</section>