Ouvidoria/Controllers/FeedbacksController.cs
using Ouvidoria.Filters;
using Ouvidoria.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class FeedbacksController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        public ActionResult Index()
        {
            ViewBag.registros = this.GetFeedbacks();
            return View();
        }

        public List<Feedback> GetFeedbacks()
        {
            return db.Feedback.Include(e => e.Departamento).Include(e => e.Usuario).ToList();
        }
    }
}

Ouvidoria/Controllers/UsuariosController.cs
using Ouvidoria.Filters;
using Ouvidoria.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Ouvidoria.Controllers
{
    [AutorizacaoFiltro("2")]
    public class UsuariosController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();
        
        public ActionResult Index()
        {
            var usuario = db.Usuario.Include(u => u.Curso).Include(u => u.UsuarioPerfil);
            return View(usuario.ToList());
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario
                              .Include(u => u.Curso)
                              .Include(u => u.UsuarioPerfil)
                              .SingleOrDefault(x => x.id == id);
                              //.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        public ActionResult Create()
        {
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome");
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Nome,Email,Telefone,idCurso,idUsuarioPerfil")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Nome,Email,Telefone,Senha, Ativo, idCurso,idUsuarioPerfil")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCurso = new SelectList(db.Curso, "id", "Nome", usuario.idCurso);
            ViewBag.idUsuarioPerfil = new SelectList(db.UsuarioPerfil, "id", "Perfil", usuario.idUsuarioPerfil);
            return View(usuario);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ouvidoria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ouvidoria</title>

    <link href="@Url.Content("/css/app.css")" rel="stylesheet">
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <link href="@Url.Content("/css/all.css")" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="https://faculdadeam.edu.br/">
                    <img src="/img/logoBranca.png" style="width: 50px;position: absolute;top: 5px;" />
                </a>
                @Html.ActionLink("Ouvidoria", "Index", new { controller = "Home" }, new { @class = "navbar-brand", id = "navBrand" })
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul id="acessos" class="nav navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Questionarios")">
                                Questionários
                                <i class="glyphicon glyphicon-comment"></i>
                            </a>
                        </li>
                        if (User.IsInRole("2"))
                        {
                            <li id="">
                                <a href="@Url.Action("Index", "Feedbacks")">
                                    Feedback
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </li>
                            <li id="">
                                <a href="@Url.Action("Index", "Depoimentos")">
                                    Depoimentos
                                    <i class="fa fa-comments"></i>
                                </a>
                            </li>
                            <li id="">
                                <a href="@Url.Action("Index", "Administracao")">
                                    Administração
                                    <i class="fa fa-cogs"></i>
                                </a>
                            </li>
                        }
                        if (User.IsInRole("1"))
                        {
                            <li class="op" url="Feedback">
                                <a href="@Url.Action("Feedback", "Ouvidoria")">
                                    Feedback
                                    <i class="glyphicon glyphicon-star"></i>
                                </a>
                            </li>
                            <li class="op" url="Elogio">
                                <a href="@Url.Action("Elogio", "Ouvidoria")">
                                    Elogio
                                    <i class="fa fa-thumbs-up"></i>
                                </a>
                            </li>
                            <li class="op" url="Sugestao">
                                <a href="@Url.Action("Sugestao", "Ouvidoria")">
                                    Sugestão
                                    <i class="fa fa-lightbulb"></i>
                                </a>
                            </li>
                            <li class="op" url="Reclamacao">
                                <a href="@Url.Action("Reclamacao", "Ouvidoria")">
                                    Reclamação
                                    <i class="fa fa-frown"></i>
                                </a>
                            </li>
                            <li class="op" url="Denuncia">
                                <a href="@Url.Action("Denuncia", "Ouvidoria")">
                                    Denúncia
                                    <i class="fa fa-bullhorn"></i>
                                </a>
                            </li>
                        }
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @User.Identity.Name <span class="caret" style="color: white;"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Alterar senha", "AlterarSenha", "PainelUsuario")</li>
                                <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li id="sidebarpage">
                            @Html.ActionLink("Login", "Login", "Autenticacao")
                        </li>
                        <li id="sidebarpage">
                            @Html.ActionLink("Registrar-se", "Cadastrar", "Autenticacao")
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()


    <footer class="page-footer font-small" style="margin: 0; padding: 15px 0; background-color: #363535; height: 125px;">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            <h2>Ouvidoria AMF</h2>
            <p style="color: white">Aqui você interage da melhor maneira com a instituição.</p>
        </div>
        <!-- Copyright -->

    </footer>

    <script src="@Url.Content("/Scripts/jquery-3.3.1.js")"></script>
    <script src="@Url.Content("/js/main.js")"></script>
    <script src="@Url.Content("/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("/js/app.js")"></script>
    @RenderSection("scripts", false)
</body>
</html>

Ouvidoria/Views/Shared/_PartialAdmSideBar.cshtml
@using (Html.BeginForm())
{
    <div class="col-md-3 col-sm-4 sidebar">
        <ul class="nav nav-stacked nav-pills" style="background-color: white;">
            <li>
                @Html.ActionLink("Página Inicial", "Index", "Home")
            </li>
            <li>
                @Html.ActionLink("Administração", "Index", "Administracao")
            </li>
            <li>
                @Html.ActionLink("Cursos", "Index", "Cursos")
            </li>
            <li>
                @Html.ActionLink("Departamentos", "Index", "Departamentos")
            </li>
            <li>
                @Html.ActionLink("Usuários", "Index", "Usuarios")
            </li>
        </ul>
    </div>
}